/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tranxactive.j2pay.gateways.parameters;

/**
 *
 * @author ilyas
 */
public enum Country {

    AF("AF", "AFG", "Afghanistan", "004"),
    AX("AX", "ALA", "Åland Islands", "248"),
    AL("AL", "ALB", "Albania", "008"),
    DZ("DZ", "DZA", "Algeria", "012"),
    AS("AS", "ASM", "American Samoa", "016"),
    AD("AD", "AND", "Andorra", "020"),
    AO("AO", "AGO", "Angola", "024"),
    AI("AI", "AIA", "Anguilla", "660"),
    AQ("AQ", "ATA", "Antarctica", "010"),
    AG("AG", "ATG", "Antigua and Barbuda", "028"),
    AR("AR", "ARG", "Argentina", "032"),
    AM("AM", "ARM", "Armenia", "051"),
    AW("AW", "ABW", "Aruba", "533"),
    AU("AU", "AUS", "Australia", "036"),
    AT("AT", "AUT", "Austria", "040"),
    AZ("AZ", "AZE", "Azerbaijan", "031"),
    BS("BS", "BHS", "Bahamas", "044"),
    BH("BH", "BHR", "Bahrain", "048"),
    BD("BD", "BGD", "Bangladesh", "050"),
    BB("BB", "BRB", "Barbados", "052"),
    BY("BY", "BLR", "Belarus", "112"),
    BE("BE", "BEL", "Belgium", "056"),
    BZ("BZ", "BLZ", "Belize", "084"),
    BJ("BJ", "BEN", "Benin", "204"),
    BM("BM", "BMU", "Bermuda", "060"),
    BT("BT", "BTN", "Bhutan", "064"),
    BO("BO", "BOL", "Bolivia (Plurinational State of)", "068"),
    BQ("BQ", "BES", "Bonaire, Sint Eustatius and Saba", "535"),
    BA("BA", "BIH", "Bosnia and Herzegovina", "070"),
    BW("BW", "BWA", "Botswana", "072"),
    BV("BV", "BVT", "Bouvet Island", "074"),
    BR("BR", "BRA", "Brazil", "076"),
    IO("IO", "IOT", "British Indian Ocean Territory", "086"),
    BN("BN", "BRN", "Brunei Darussalam", "096"),
    BG("BG", "BGR", "Bulgaria", "100"),
    BF("BF", "BFA", "Burkina Faso", "854"),
    BI("BI", "BDI", "Burundi", "108"),
    CV("CV", "CPV", "Cabo Verde", "132"),
    KH("KH", "KHM", "Cambodia", "116"),
    CM("CM", "CMR", "Cameroon", "120"),
    CA("CA", "CAN", "Canada", "124"),
    KY("KY", "CYM", "Cayman Islands", "136"),
    CF("CF", "CAF", "Central African Republic", "140"),
    TD("TD", "TCD", "Chad", "148"),
    CL("CL", "CHL", "Chile", "152"),
    CN("CN", "CHN", "China", "156"),
    CX("CX", "CXR", "Christmas Island", "162"),
    CC("CC", "CCK", "Cocos (Keeling) Islands", "166"),
    CO("CO", "COL", "Colombia", "170"),
    KM("KM", "COM", "Comoros", "174"),
    CG("CG", "COG", "Congo", "178"),
    CD("CD", "COD", "Congo (Democratic Republic of the)", "180"),
    CK("CK", "COK", "Cook Islands", "184"),
    CR("CR", "CRI", "Costa Rica", "188"),
    CI("CI", "CIV", "Côte d'Ivoire", "384"),
    HR("HR", "HRV", "Croatia", "191"),
    CU("CU", "CUB", "Cuba", "192"),
    CW("CW", "CUW", "Curaçao", "531"),
    CY("CY", "CYP", "Cyprus", "196"),
    CZ("CZ", "CZE", "Czechia", "203"),
    DK("DK", "DNK", "Denmark", "208"),
    DJ("DJ", "DJI", "Djibouti", "262"),
    DM("DM", "DMA", "Dominica", "212"),
    DO("DO", "DOM", "Dominican Republic", "214"),
    EC("EC", "ECU", "Ecuador", "218"),
    EG("EG", "EGY", "Egypt", "818"),
    SV("SV", "SLV", "El Salvador", "222"),
    GQ("GQ", "GNQ", "Equatorial Guinea", "226"),
    ER("ER", "ERI", "Eritrea", "232"),
    EE("EE", "EST", "Estonia", "233"),
    ET("ET", "ETH", "Ethiopia", "231"),
    FK("FK", "FLK", "Falkland Islands (Malvinas)", "238"),
    FO("FO", "FRO", "Faroe Islands", "234"),
    FJ("FJ", "FJI", "Fiji", "242"),
    FI("FI", "FIN", "Finland", "246"),
    FR("FR", "FRA", "France", "250"),
    GF("GF", "GUF", "French Guiana", "254"),
    PF("PF", "PYF", "French Polynesia", "258"),
    TF("TF", "ATF", "French Southern Territories", "260"),
    GA("GA", "GAB", "Gabon", "266"),
    GM("GM", "GMB", "Gambia", "270"),
    GE("GE", "GEO", "Georgia", "268"),
    DE("DE", "DEU", "Germany", "276"),
    GH("GH", "GHA", "Ghana", "288"),
    GI("GI", "GIB", "Gibraltar", "292"),
    GR("GR", "GRC", "Greece", "300"),
    GL("GL", "GRL", "Greenland", "304"),
    GD("GD", "GRD", "Grenada", "308"),
    GP("GP", "GLP", "Guadeloupe", "312"),
    GU("GU", "GUM", "Guam", "316"),
    GT("GT", "GTM", "Guatemala", "320"),
    GG("GG", "GGY", "Guernsey", "831"),
    GN("GN", "GIN", "Guinea", "324"),
    GW("GW", "GNB", "Guinea-Bissau", "624"),
    GY("GY", "GUY", "Guyana", "328"),
    HT("HT", "HTI", "Haiti", "332"),
    HM("HM", "HMD", "Heard Island and McDonald Islands", "334"),
    VA("VA", "VAT", "Holy See", "336"),
    HN("HN", "HND", "Honduras", "340"),
    HK("HK", "HKG", "Hong Kong", "344"),
    HU("HU", "HUN", "Hungary", "348"),
    IS("IS", "ISL", "Iceland", "352"),
    IN("IN", "IND", "India", "356"),
    ID("ID", "IDN", "Indonesia", "360"),
    IR("IR", "IRN", "Iran (Islamic Republic of)", "364"),
    IQ("IQ", "IRQ", "Iraq", "368"),
    IE("IE", "IRL", "Ireland", "372"),
    IM("IM", "IMN", "Isle of Man", "833"),
    IL("IL", "ISR", "Israel", "376"),
    IT("IT", "ITA", "Italy", "380"),
    JM("JM", "JAM", "Jamaica", "388"),
    JP("JP", "JPN", "Japan", "392"),
    JE("JE", "JEY", "Jersey", "832"),
    JO("JO", "JOR", "Jordan", "400"),
    KZ("KZ", "KAZ", "Kazakhstan", "398"),
    KE("KE", "KEN", "Kenya", "404"),
    KI("KI", "KIR", "Kiribati", "296"),
    KP("KP", "PRK", "Korea (Democratic People's Republic of)", "408"),
    KR("KR", "KOR", "Korea (Republic of)", "410"),
    KW("KW", "KWT", "Kuwait", "414"),
    KG("KG", "KGZ", "Kyrgyzstan", "417"),
    LA("LA", "LAO", "Lao People's Democratic Republic", "418"),
    LV("LV", "LVA", "Latvia", "428"),
    LB("LB", "LBN", "Lebanon", "422"),
    LS("LS", "LSO", "Lesotho", "426"),
    LR("LR", "LBR", "Liberia", "430"),
    LY("LY", "LBY", "Libya", "434"),
    LI("LI", "LIE", "Liechtenstein", "438"),
    LT("LT", "LTU", "Lithuania", "440"),
    LU("LU", "LUX", "Luxembourg", "442"),
    MO("MO", "MAC", "Macao", "446"),
    MK("MK", "MKD", "Macedonia (the former Yugoslav Republic of)", "807"),
    MG("MG", "MDG", "Madagascar", "450"),
    MW("MW", "MWI", "Malawi", "454"),
    MY("MY", "MYS", "Malaysia", "458"),
    MV("MV", "MDV", "Maldives", "462"),
    ML("ML", "MLI", "Mali", "466"),
    MT("MT", "MLT", "Malta", "470"),
    MH("MH", "MHL", "Marshall Islands", "584"),
    MQ("MQ", "MTQ", "Martinique", "474"),
    MR("MR", "MRT", "Mauritania", "478"),
    MU("MU", "MUS", "Mauritius", "480"),
    YT("YT", "MYT", "Mayotte", "175"),
    MX("MX", "MEX", "Mexico", "484"),
    FM("FM", "FSM", "Micronesia (Federated States of)", "583"),
    MD("MD", "MDA", "Moldova (Republic of)", "498"),
    MC("MC", "MCO", "Monaco", "492"),
    MN("MN", "MNG", "Mongolia", "496"),
    ME("ME", "MNE", "Montenegro", "499"),
    MS("MS", "MSR", "Montserrat", "500"),
    MA("MA", "MAR", "Morocco", "504"),
    MZ("MZ", "MOZ", "Mozambique", "508"),
    MM("MM", "MMR", "Myanmar", "104"),
    NA("NA", "NAM", "Namibia", "516"),
    NR("NR", "NRU", "Nauru", "520"),
    NP("NP", "NPL", "Nepal", "524"),
    NL("NL", "NLD", "Netherlands", "528"),
    NC("NC", "NCL", "New Caledonia", "540"),
    NZ("NZ", "NZL", "New Zealand", "554"),
    NI("NI", "NIC", "Nicaragua", "558"),
    NE("NE", "NER", "Niger", "562"),
    NG("NG", "NGA", "Nigeria", "566"),
    NU("NU", "NIU", "Niue", "570"),
    NF("NF", "NFK", "Norfolk Island", "574"),
    MP("MP", "MNP", "Northern Mariana Islands", "580"),
    NO("NO", "NOR", "Norway", "578"),
    OM("OM", "OMN", "Oman", "512"),
    PK("PK", "PAK", "Pakistan", "586"),
    PW("PW", "PLW", "Palau", "585"),
    PS("PS", "PSE", "Palestine, State of", "275"),
    PA("PA", "PAN", "Panama", "591"),
    PG("PG", "PNG", "Papua New Guinea", "598"),
    PY("PY", "PRY", "Paraguay", "600"),
    PE("PE", "PER", "Peru", "604"),
    PH("PH", "PHL", "Philippines", "608"),
    PN("PN", "PCN", "Pitcairn", "612"),
    PL("PL", "POL", "Poland", "616"),
    PT("PT", "PRT", "Portugal", "620"),
    PR("PR", "PRI", "Puerto Rico", "630"),
    QA("QA", "QAT", "Qatar", "634"),
    RE("RE", "REU", "Réunion", "638"),
    RO("RO", "ROU", "Romania", "642"),
    RU("RU", "RUS", "Russian Federation", "643"),
    RW("RW", "RWA", "Rwanda", "646"),
    BL("BL", "BLM", "Saint Barthélemy", "652"),
    SH("SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha", "654"),
    KN("KN", "KNA", "Saint Kitts and Nevis", "659"),
    LC("LC", "LCA", "Saint Lucia", "662"),
    MF("MF", "MAF", "Saint Martin (French part)", "663"),
    PM("PM", "SPM", "Saint Pierre and Miquelon", "666"),
    VC("VC", "VCT", "Saint Vincent and the Grenadines", "670"),
    WS("WS", "WSM", "Samoa", "882"),
    SM("SM", "SMR", "San Marino", "674"),
    ST("ST", "STP", "Sao Tome and Principe", "678"),
    SA("SA", "SAU", "Saudi Arabia", "682"),
    SN("SN", "SEN", "Senegal", "686"),
    RS("RS", "SRB", "Serbia", "688"),
    SC("SC", "SYC", "Seychelles", "690"),
    SL("SL", "SLE", "Sierra Leone", "694"),
    SG("SG", "SGP", "Singapore", "702"),
    SX("SX", "SXM", "Sint Maarten (Dutch part)", "534"),
    SK("SK", "SVK", "Slovakia", "703"),
    SI("SI", "SVN", "Slovenia", "705"),
    SB("SB", "SLB", "Solomon Islands", "090"),
    SO("SO", "SOM", "Somalia", "706"),
    ZA("ZA", "ZAF", "South Africa", "710"),
    GS("GS", "SGS", "South Georgia and the South Sandwich Islands", "239"),
    SS("SS", "SSD", "South Sudan", "728"),
    ES("ES", "ESP", "Spain", "724"),
    LK("LK", "LKA", "Sri Lanka", "144"),
    SD("SD", "SDN", "Sudan", "729"),
    SR("SR", "SUR", "Suriname", "740"),
    SJ("SJ", "SJM", "Svalbard and Jan Mayen", "744"),
    SZ("SZ", "SWZ", "Swaziland", "748"),
    SE("SE", "SWE", "Sweden", "752"),
    CH("CH", "CHE", "Switzerland", "756"),
    SY("SY", "SYR", "Syrian Arab Republic", "760"),
    TW("TW", "TWN", "Taiwan, Province of China[a]", "158"),
    TJ("TJ", "TJK", "Tajikistan", "762"),
    TZ("TZ", "TZA", "Tanzania, United Republic of", "834"),
    TH("TH", "THA", "Thailand", "764"),
    TL("TL", "TLS", "Timor-Leste", "626"),
    TG("TG", "TGO", "Togo", "768"),
    TK("TK", "TKL", "Tokelau", "772"),
    TO("TO", "TON", "Tonga", "776"),
    TT("TT", "TTO", "Trinidad and Tobago", "780"),
    TN("TN", "TUN", "Tunisia", "788"),
    TR("TR", "TUR", "Turkey", "792"),
    TM("TM", "TKM", "Turkmenistan", "795"),
    TC("TC", "TCA", "Turks and Caicos Islands", "796"),
    TV("TV", "TUV", "Tuvalu", "798"),
    UG("UG", "UGA", "Uganda", "800"),
    UA("UA", "UKR", "Ukraine", "804"),
    AE("AE", "ARE", "United Arab Emirates", "784"),
    GB("GB", "GBR", "United Kingdom of Great Britain and Northern Ireland", "826"),
    US("US", "USA", "United States of America", "840"),
    UM("UM", "UMI", "United States Minor Outlying Islands", "581"),
    UY("UY", "URY", "Uruguay", "858"),
    UZ("UZ", "UZB", "Uzbekistan", "860"),
    VU("VU", "VUT", "Vanuatu", "548"),
    VE("VE", "VEN", "Venezuela (Bolivarian Republic of)", "862"),
    VN("VN", "VNM", "Viet Nam", "704"),
    VG("VG", "VGB", "Virgin Islands (British)", "092"),
    VI("VI", "VIR", "Virgin Islands (U.S.)", "850"),
    WF("WF", "WLF", "Wallis and Futuna", "876"),
    EH("EH", "ESH", "Western Sahara", "732"),
    YE("YE", "YEM", "Yemen", "887"),
    ZM("ZM", "ZMB", "Zambia", "894"),
    ZW("ZW", "ZWE", "Zimbabwe", "716"),
    AFG("AF", "AFG", "Afghanistan", "004"),
    ALA("AX", "ALA", "Åland Islands", "248"),
    ALB("AL", "ALB", "Albania", "008"),
    DZA("DZ", "DZA", "Algeria", "012"),
    ASM("AS", "ASM", "American Samoa", "016"),
    AND("AD", "AND", "Andorra", "020"),
    AGO("AO", "AGO", "Angola", "024"),
    AIA("AI", "AIA", "Anguilla", "660"),
    ATA("AQ", "ATA", "Antarctica", "010"),
    ATG("AG", "ATG", "Antigua and Barbuda", "028"),
    ARG("AR", "ARG", "Argentina", "032"),
    ARM("AM", "ARM", "Armenia", "051"),
    ABW("AW", "ABW", "Aruba", "533"),
    AUS("AU", "AUS", "Australia", "036"),
    AUT("AT", "AUT", "Austria", "040"),
    AZE("AZ", "AZE", "Azerbaijan", "031"),
    BHS("BS", "BHS", "Bahamas", "044"),
    BHR("BH", "BHR", "Bahrain", "048"),
    BGD("BD", "BGD", "Bangladesh", "050"),
    BRB("BB", "BRB", "Barbados", "052"),
    BLR("BY", "BLR", "Belarus", "112"),
    BEL("BE", "BEL", "Belgium", "056"),
    BLZ("BZ", "BLZ", "Belize", "084"),
    BEN("BJ", "BEN", "Benin", "204"),
    BMU("BM", "BMU", "Bermuda", "060"),
    BTN("BT", "BTN", "Bhutan", "064"),
    BOL("BO", "BOL", "Bolivia (Plurinational State of)", "068"),
    BES("BQ", "BES", "Bonaire, Sint Eustatius and Saba", "535"),
    BIH("BA", "BIH", "Bosnia and Herzegovina", "070"),
    BWA("BW", "BWA", "Botswana", "072"),
    BVT("BV", "BVT", "Bouvet Island", "074"),
    BRA("BR", "BRA", "Brazil", "076"),
    IOT("IO", "IOT", "British Indian Ocean Territory", "086"),
    BRN("BN", "BRN", "Brunei Darussalam", "096"),
    BGR("BG", "BGR", "Bulgaria", "100"),
    BFA("BF", "BFA", "Burkina Faso", "854"),
    BDI("BI", "BDI", "Burundi", "108"),
    CPV("CV", "CPV", "Cabo Verde", "132"),
    KHM("KH", "KHM", "Cambodia", "116"),
    CMR("CM", "CMR", "Cameroon", "120"),
    CAN("CA", "CAN", "Canada", "124"),
    CYM("KY", "CYM", "Cayman Islands", "136"),
    CAF("CF", "CAF", "Central African Republic", "140"),
    TCD("TD", "TCD", "Chad", "148"),
    CHL("CL", "CHL", "Chile", "152"),
    CHN("CN", "CHN", "China", "156"),
    CXR("CX", "CXR", "Christmas Island", "162"),
    CCK("CC", "CCK", "Cocos (Keeling) Islands", "166"),
    COL("CO", "COL", "Colombia", "170"),
    COM("KM", "COM", "Comoros", "174"),
    COG("CG", "COG", "Congo", "178"),
    COD("CD", "COD", "Congo (Democratic Republic of the)", "180"),
    COK("CK", "COK", "Cook Islands", "184"),
    CRI("CR", "CRI", "Costa Rica", "188"),
    CIV("CI", "CIV", "Côte d'Ivoire", "384"),
    HRV("HR", "HRV", "Croatia", "191"),
    CUB("CU", "CUB", "Cuba", "192"),
    CUW("CW", "CUW", "Curaçao", "531"),
    CYP("CY", "CYP", "Cyprus", "196"),
    CZE("CZ", "CZE", "Czechia", "203"),
    DNK("DK", "DNK", "Denmark", "208"),
    DJI("DJ", "DJI", "Djibouti", "262"),
    DMA("DM", "DMA", "Dominica", "212"),
    DOM("DO", "DOM", "Dominican Republic", "214"),
    ECU("EC", "ECU", "Ecuador", "218"),
    EGY("EG", "EGY", "Egypt", "818"),
    SLV("SV", "SLV", "El Salvador", "222"),
    GNQ("GQ", "GNQ", "Equatorial Guinea", "226"),
    ERI("ER", "ERI", "Eritrea", "232"),
    EST("EE", "EST", "Estonia", "233"),
    ETH("ET", "ETH", "Ethiopia", "231"),
    FLK("FK", "FLK", "Falkland Islands (Malvinas)", "238"),
    FRO("FO", "FRO", "Faroe Islands", "234"),
    FJI("FJ", "FJI", "Fiji", "242"),
    FIN("FI", "FIN", "Finland", "246"),
    FRA("FR", "FRA", "France", "250"),
    GUF("GF", "GUF", "French Guiana", "254"),
    PYF("PF", "PYF", "French Polynesia", "258"),
    ATF("TF", "ATF", "French Southern Territories", "260"),
    GAB("GA", "GAB", "Gabon", "266"),
    GMB("GM", "GMB", "Gambia", "270"),
    GEO("GE", "GEO", "Georgia", "268"),
    DEU("DE", "DEU", "Germany", "276"),
    GHA("GH", "GHA", "Ghana", "288"),
    GIB("GI", "GIB", "Gibraltar", "292"),
    GRC("GR", "GRC", "Greece", "300"),
    GRL("GL", "GRL", "Greenland", "304"),
    GRD("GD", "GRD", "Grenada", "308"),
    GLP("GP", "GLP", "Guadeloupe", "312"),
    GUM("GU", "GUM", "Guam", "316"),
    GTM("GT", "GTM", "Guatemala", "320"),
    GGY("GG", "GGY", "Guernsey", "831"),
    GIN("GN", "GIN", "Guinea", "324"),
    GNB("GW", "GNB", "Guinea-Bissau", "624"),
    GUY("GY", "GUY", "Guyana", "328"),
    HTI("HT", "HTI", "Haiti", "332"),
    HMD("HM", "HMD", "Heard Island and McDonald Islands", "334"),
    VAT("VA", "VAT", "Holy See", "336"),
    HND("HN", "HND", "Honduras", "340"),
    HKG("HK", "HKG", "Hong Kong", "344"),
    HUN("HU", "HUN", "Hungary", "348"),
    ISL("IS", "ISL", "Iceland", "352"),
    IND("IN", "IND", "India", "356"),
    IDN("ID", "IDN", "Indonesia", "360"),
    IRN("IR", "IRN", "Iran (Islamic Republic of)", "364"),
    IRQ("IQ", "IRQ", "Iraq", "368"),
    IRL("IE", "IRL", "Ireland", "372"),
    IMN("IM", "IMN", "Isle of Man", "833"),
    ISR("IL", "ISR", "Israel", "376"),
    ITA("IT", "ITA", "Italy", "380"),
    JAM("JM", "JAM", "Jamaica", "388"),
    JPN("JP", "JPN", "Japan", "392"),
    JEY("JE", "JEY", "Jersey", "832"),
    JOR("JO", "JOR", "Jordan", "400"),
    KAZ("KZ", "KAZ", "Kazakhstan", "398"),
    KEN("KE", "KEN", "Kenya", "404"),
    KIR("KI", "KIR", "Kiribati", "296"),
    PRK("KP", "PRK", "Korea (Democratic People's Republic of)", "408"),
    KOR("KR", "KOR", "Korea (Republic of)", "410"),
    KWT("KW", "KWT", "Kuwait", "414"),
    KGZ("KG", "KGZ", "Kyrgyzstan", "417"),
    LAO("LA", "LAO", "Lao People's Democratic Republic", "418"),
    LVA("LV", "LVA", "Latvia", "428"),
    LBN("LB", "LBN", "Lebanon", "422"),
    LSO("LS", "LSO", "Lesotho", "426"),
    LBR("LR", "LBR", "Liberia", "430"),
    LBY("LY", "LBY", "Libya", "434"),
    LIE("LI", "LIE", "Liechtenstein", "438"),
    LTU("LT", "LTU", "Lithuania", "440"),
    LUX("LU", "LUX", "Luxembourg", "442"),
    MAC("MO", "MAC", "Macao", "446"),
    MKD("MK", "MKD", "Macedonia (the former Yugoslav Republic of)", "807"),
    MDG("MG", "MDG", "Madagascar", "450"),
    MWI("MW", "MWI", "Malawi", "454"),
    MYS("MY", "MYS", "Malaysia", "458"),
    MDV("MV", "MDV", "Maldives", "462"),
    MLI("ML", "MLI", "Mali", "466"),
    MLT("MT", "MLT", "Malta", "470"),
    MHL("MH", "MHL", "Marshall Islands", "584"),
    MTQ("MQ", "MTQ", "Martinique", "474"),
    MRT("MR", "MRT", "Mauritania", "478"),
    MUS("MU", "MUS", "Mauritius", "480"),
    MYT("YT", "MYT", "Mayotte", "175"),
    MEX("MX", "MEX", "Mexico", "484"),
    FSM("FM", "FSM", "Micronesia (Federated States of)", "583"),
    MDA("MD", "MDA", "Moldova (Republic of)", "498"),
    MCO("MC", "MCO", "Monaco", "492"),
    MNG("MN", "MNG", "Mongolia", "496"),
    MNE("ME", "MNE", "Montenegro", "499"),
    MSR("MS", "MSR", "Montserrat", "500"),
    MAR("MA", "MAR", "Morocco", "504"),
    MOZ("MZ", "MOZ", "Mozambique", "508"),
    MMR("MM", "MMR", "Myanmar", "104"),
    NAM("NA", "NAM", "Namibia", "516"),
    NRU("NR", "NRU", "Nauru", "520"),
    NPL("NP", "NPL", "Nepal", "524"),
    NLD("NL", "NLD", "Netherlands", "528"),
    NCL("NC", "NCL", "New Caledonia", "540"),
    NZL("NZ", "NZL", "New Zealand", "554"),
    NIC("NI", "NIC", "Nicaragua", "558"),
    NER("NE", "NER", "Niger", "562"),
    NGA("NG", "NGA", "Nigeria", "566"),
    NIU("NU", "NIU", "Niue", "570"),
    NFK("NF", "NFK", "Norfolk Island", "574"),
    MNP("MP", "MNP", "Northern Mariana Islands", "580"),
    NOR("NO", "NOR", "Norway", "578"),
    OMN("OM", "OMN", "Oman", "512"),
    PAK("PK", "PAK", "Pakistan", "586"),
    PLW("PW", "PLW", "Palau", "585"),
    PSE("PS", "PSE", "Palestine, State of", "275"),
    PAN("PA", "PAN", "Panama", "591"),
    PNG("PG", "PNG", "Papua New Guinea", "598"),
    PRY("PY", "PRY", "Paraguay", "600"),
    PER("PE", "PER", "Peru", "604"),
    PHL("PH", "PHL", "Philippines", "608"),
    PCN("PN", "PCN", "Pitcairn", "612"),
    POL("PL", "POL", "Poland", "616"),
    PRT("PT", "PRT", "Portugal", "620"),
    PRI("PR", "PRI", "Puerto Rico", "630"),
    QAT("QA", "QAT", "Qatar", "634"),
    REU("RE", "REU", "Réunion", "638"),
    ROU("RO", "ROU", "Romania", "642"),
    RUS("RU", "RUS", "Russian Federation", "643"),
    RWA("RW", "RWA", "Rwanda", "646"),
    BLM("BL", "BLM", "Saint Barthélemy", "652"),
    SHN("SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha", "654"),
    KNA("KN", "KNA", "Saint Kitts and Nevis", "659"),
    LCA("LC", "LCA", "Saint Lucia", "662"),
    MAF("MF", "MAF", "Saint Martin (French part)", "663"),
    SPM("PM", "SPM", "Saint Pierre and Miquelon", "666"),
    VCT("VC", "VCT", "Saint Vincent and the Grenadines", "670"),
    WSM("WS", "WSM", "Samoa", "882"),
    SMR("SM", "SMR", "San Marino", "674"),
    STP("ST", "STP", "Sao Tome and Principe", "678"),
    SAU("SA", "SAU", "Saudi Arabia", "682"),
    SEN("SN", "SEN", "Senegal", "686"),
    SRB("RS", "SRB", "Serbia", "688"),
    SYC("SC", "SYC", "Seychelles", "690"),
    SLE("SL", "SLE", "Sierra Leone", "694"),
    SGP("SG", "SGP", "Singapore", "702"),
    SXM("SX", "SXM", "Sint Maarten (Dutch part)", "534"),
    SVK("SK", "SVK", "Slovakia", "703"),
    SVN("SI", "SVN", "Slovenia", "705"),
    SLB("SB", "SLB", "Solomon Islands", "090"),
    SOM("SO", "SOM", "Somalia", "706"),
    ZAF("ZA", "ZAF", "South Africa", "710"),
    SGS("GS", "SGS", "South Georgia and the South Sandwich Islands", "239"),
    SSD("SS", "SSD", "South Sudan", "728"),
    ESP("ES", "ESP", "Spain", "724"),
    LKA("LK", "LKA", "Sri Lanka", "144"),
    SDN("SD", "SDN", "Sudan", "729"),
    SUR("SR", "SUR", "Suriname", "740"),
    SJM("SJ", "SJM", "Svalbard and Jan Mayen", "744"),
    SWZ("SZ", "SWZ", "Swaziland", "748"),
    SWE("SE", "SWE", "Sweden", "752"),
    CHE("CH", "CHE", "Switzerland", "756"),
    SYR("SY", "SYR", "Syrian Arab Republic", "760"),
    TWN("TW", "TWN", "Taiwan, Province of China[a]", "158"),
    TJK("TJ", "TJK", "Tajikistan", "762"),
    TZA("TZ", "TZA", "Tanzania, United Republic of", "834"),
    THA("TH", "THA", "Thailand", "764"),
    TLS("TL", "TLS", "Timor-Leste", "626"),
    TGO("TG", "TGO", "Togo", "768"),
    TKL("TK", "TKL", "Tokelau", "772"),
    TON("TO", "TON", "Tonga", "776"),
    TTO("TT", "TTO", "Trinidad and Tobago", "780"),
    TUN("TN", "TUN", "Tunisia", "788"),
    TUR("TR", "TUR", "Turkey", "792"),
    TKM("TM", "TKM", "Turkmenistan", "795"),
    TCA("TC", "TCA", "Turks and Caicos Islands", "796"),
    TUV("TV", "TUV", "Tuvalu", "798"),
    UGA("UG", "UGA", "Uganda", "800"),
    UKR("UA", "UKR", "Ukraine", "804"),
    ARE("AE", "ARE", "United Arab Emirates", "784"),
    GBR("GB", "GBR", "United Kingdom of Great Britain and Northern Ireland", "826"),
    USA("US", "USA", "United States of America", "840"),
    UMI("UM", "UMI", "United States Minor Outlying Islands", "581"),
    URY("UY", "URY", "Uruguay", "858"),
    UZB("UZ", "UZB", "Uzbekistan", "860"),
    VUT("VU", "VUT", "Vanuatu", "548"),
    VEN("VE", "VEN", "Venezuela (Bolivarian Republic of)", "862"),
    VNM("VN", "VNM", "Viet Nam", "704"),
    VGB("VG", "VGB", "Virgin Islands (British)", "092"),
    VIR("VI", "VIR", "Virgin Islands (U.S.)", "850"),
    WLF("WF", "WLF", "Wallis and Futuna", "876"),
    ESH("EH", "ESH", "Western Sahara", "732"),
    YEM("YE", "YEM", "Yemen", "887"),
    ZMB("ZM", "ZMB", "Zambia", "894"),
    ZWE("ZW", "ZWE", "Zimbabwe", "716");

    private String codeISO2, codeISO3, name, numericCode;

    Country(String codeAplha2, String codeAlpha3, String fullName, String numericCode) {
        this.codeISO2 = codeAplha2;
        this.codeISO3 = codeAlpha3;
        this.name = fullName;
        this.numericCode = numericCode;
    }

    /**
     * @return the codeISO2
     */
    public String getCodeISO2() {
        return codeISO2;
    }

    /**
     * @param codeISO2 the codeISO2 to set
     */
    public void setCodeISO2(String codeISO2) {
        this.codeISO2 = codeISO2;
    }

    /**
     * @return the codeISO3
     */
    public String getCodeISO3() {
        return codeISO3;
    }

    /**
     * @param codeISO3 the codeISO3 to set
     */
    public void setCodeISO3(String codeISO3) {
        this.codeISO3 = codeISO3;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the numericCode
     */
    public String getNumericCode() {
        return numericCode;
    }

    /**
     * @param numericCode the numericCode to set
     */
    public void setNumericCode(String numericCode) {
        this.numericCode = numericCode;
    }

}
